version: "3.5"
services:
  postgresql:
    image: postgres:${POSTGRESQL_VERSION}
    networks:
      - temporal-network
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
    ports:
      - "5432:5432"
    volumes:
      # Use a named volume for persistent data
      - postgres-data:/var/lib/postgresql/data

  temporal:
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    networks:
      - temporal-network
    ports:
      - "7233:7233"
    environment:
      # Corrected connection details
      - DB=postgresql
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_HOST=postgresql
      - POSTGRES_DB=temporal
    depends_on:
      - postgresql

  temporal-ui:
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    networks:
      - temporal-network
    ports:
      # Changed to a non-conflicting port
      - "8088:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal

  temporal-admin-tools:
    image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
    networks:
      - temporal-network
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    stdin_open: true
    tty: true
    depends_on:
      - temporal

# Define the network and the named volume
networks:
  temporal-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
